function [fitresult] = createFit1(times, Ambulation)
%CREATEFIT1(TIMES,AMBULATION)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : times
%      Y Output: Ambulation
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Nov-2011 20:35:25


%% Fit: 'untitled fit 1'.
try
    [xData, yData] = prepareCurveData( times, Ambulation );
    
    % Set up fittype and options.
    ft = fittype( 'poly1' );
    opts = fitoptions( ft );
    opts.Lower = [-Inf -Inf];
    opts.Upper = [Inf Inf];
    
    % Fit model to data.
    [fitresult, gof] = fit( xData, yData, ft, opts );
    
    % Plot fit with data.
    % figure( 'Name', 'untitled fit 1' );
    % h = plot( fitresult, xData, yData );
    % equation = ['Average speed = ' num2str(fitresult.p1) ' pixels/second'];
    % legend( h, equation, 'Location', 'Best' );
    % % Label axes
    % xlabel( 'Time (s)' );
    % ylabel( 'Ambulation (cumulative distance, pixels)' );
    %
    %
catch
    P = polyfit(times,Ambulation,1);
    fitresult.p1 = P(1);
    fitresult.p2 = P(2);
end